import type { InventoryItem } from "@/lib/types"

// Deep-cloned on every read so demo-mode mutations never leak between requests
// in long-lived dev processes while still behaving like a real data store
// within a single request lifecycle.
export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "demo-001",
    itemName: "Corrugated Shipping Box (Medium)",
    sku: "BOX-MED-100",
    quantity: 42,
    reorderThreshold: 75,
    unitPrice: 1.25,
    supplierEmail: "orders@packrightsupply.com",
  },
  {
    id: "demo-002",
    itemName: "Heavy-Duty Packing Tape",
    sku: "TAPE-HD-048",
    quantity: 210,
    reorderThreshold: 60,
    unitPrice: 3.4,
    supplierEmail: "orders@packrightsupply.com",
  },
  {
    id: "demo-003",
    itemName: "Bubble Wrap Roll (12in x 100ft)",
    sku: "WRAP-BUB-012",
    quantity: 18,
    reorderThreshold: 20,
    unitPrice: 24.99,
    supplierEmail: "sales@cushionpro.com",
  },
  {
    id: "demo-004",
    itemName: "Nitrile Gloves (Box of 100)",
    sku: "GLV-NIT-100",
    quantity: 96,
    reorderThreshold: 40,
    unitPrice: 8.75,
    supplierEmail: "b2b@safehandsupply.com",
  },
  {
    id: "demo-005",
    itemName: "Thermal Shipping Labels (4x6, 500ct)",
    sku: "LBL-THM-500",
    quantity: 12,
    reorderThreshold: 30,
    unitPrice: 14.5,
    supplierEmail: "orders@labelworksco.com",
  },
  {
    id: "demo-006",
    itemName: "Stretch Wrap Film (18in)",
    sku: "WRAP-STR-018",
    quantity: 55,
    reorderThreshold: 25,
    unitPrice: 11.2,
    supplierEmail: "sales@cushionpro.com",
  },
  {
    id: "demo-007",
    itemName: "Zip Ties (12in, Pack of 100)",
    sku: "ZIP-012-100",
    quantity: 8,
    reorderThreshold: 15,
    unitPrice: 6.1,
    supplierEmail: "b2b@safehandsupply.com",
  },
  {
    id: "demo-008",
    itemName: "Warehouse Barcode Scanner",
    sku: "SCN-BAR-002",
    quantity: 6,
    reorderThreshold: 3,
    unitPrice: 189.0,
    supplierEmail: "procurement@scandirect.com",
  },
  {
    id: "demo-009",
    itemName: "Pallet Wrap Dispenser",
    sku: "DSP-PLT-001",
    quantity: 4,
    reorderThreshold: 5,
    unitPrice: 42.3,
    supplierEmail: "orders@packrightsupply.com",
  },
  {
    id: "demo-010",
    itemName: "Anti-Static Foam Sheets",
    sku: "FOAM-AS-024",
    quantity: 130,
    reorderThreshold: 50,
    unitPrice: 2.15,
    supplierEmail: "sales@cushionpro.com",
  },
]
